kumuluzee:
  name: schedule-service
  version: 1.0.0
  env:
    name: dev

  health:
    checks:
      disk-space-health-check:
        threshold: 100000000

  metrics:
    jvm:
      enabled: true
    web-instrumentation:
      - name: schedule-endpoint
        url-pattern: /schedule/*


health:
  health-check-http-method: HEAD
